### ISSUE TITLE
Add an string tag when using Objects as tags

### ISSUE THREAD

**Issue by gabrielslau** [bootstrap-tagsinput/bootstrap-tagsinput#274] opened 2014-12-31 06:47 UTC
Hi,

I realized that when I use the **Object as tags**, the default behavior of the plugin crashes. You can no longer insert a new element by typing on the inputText.

The event 'beforeItemAdd' does not detect the new tag string to be able to turn into an object before inserting the value.

Is there any way to set this up or is it a bug?

**Comment by amine-bouassida** [comment] 2015-01-06 14:39
+1
I think that it's not a bug. Logically, if your array of values is built with custom objects, the fact that you want to add to it a simple string as an object would affect the homogeneity of your collection.
Me too I have the same need and I think that we could overcome this limitation by adding the possibility to place a callback that will be in charge of formatting and adding the new value to the existing collection, allowing us to avoid the homogeneity matter. And if this new callback is given as an argument when calling the plugin, it replaces the default behavior, that simply adds the new tag as a string.
I am not yet sure that the feature doesn't already exist, I have to read the code first. If my assumption and solution work out, I will put in a pull request with the changes.

**Comment by ajanini** [comment] 2015-02-26 17:41
+1

**Comment by mediavrog** [comment] 2015-04-16 09:38
+1 for being able to add free tags with objects

**Closed** 2022-04-05 11:41 UTC
